pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...!"
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
            
        }
        stage('Deploy In Staging Environment'){
            steps {
                build job: 'Deploy-Application-On-Staging-Environment'

            }
            
        }


    }
}