pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...!"
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
            
        }
        stage('Deploy In Staging Environment'){
            steps {
                build job: 'Deploy-Application-On-Staging-Environment'

            }
            
        }
        stage('Deploy In Production'){
            steps {
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve PRODUCTION deployment..?'
                }
                build job: 'Deploy-Application-On-Prod-Environment'

        }
            
            }


    }
}